spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-profile
    username: postgres
    password: root

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8082